package com.batanasov.javaTransportCompanyProjectSPRING.DTO;

import lombok.Data;
/**
 * Data Transfer Object (DTO) for representing the total revenue generated by an employee through transport contracts.
 * This DTO is used to aggregate and transfer data related to the total revenue generated by an employee from their associated transport contracts.
 */
@Data
public class EmployeeRevenueDTO {
    private Long employeeId;
    private String employeeName;
    private Double totalRevenue;

    public EmployeeRevenueDTO(Long employeeId, String employeeName, Double totalRevenue) {
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.totalRevenue = totalRevenue;
    }

    public EmployeeRevenueDTO() {
    }
}